name: Publish to npm

on:
  push:
    branches:
      - main  # Hoặc nhánh chính của bạn

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Cập nhật lên phiên bản mới nhất nếu cần

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Cập nhật lên Node.js 20 để tương thích
          
      - name: Install dependencies
        run: npm install

      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Sử dụng token từ GitHub Secrets
        run: |
          npm version patch  # Cập nhật số phiên bản
          npm publish --access public
